# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='project.User'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='favorites',
            field=models.ManyToManyField(related_name='users', to='project.User'),
        ),
    ]
